import { readFileSync } from "fs";

const AYRSHARE_API_KEY = process.env.AYRSHARE_API_KEY;

if (!AYRSHARE_API_KEY) {
  console.error(JSON.stringify({ status: "FAILED", role: "Output(Distribution)", error: "Missing AYRSHARE_API_KEY" }, null, 2));
  process.exit(1);
}

async function run() {
  try {
    // 1. Read input payload (Triggered after Telegram Approval callback in n8n)
    let inputStr = "";
    if (process.argv.length > 2) {
      inputStr = readFileSync(process.argv[2], "utf8");
    } else {
      inputStr = await Bun.stdin.text();
    }

    if (!inputStr.trim()) {
      throw new Error("No payload received from Static Renderer.");
    }

    const inputData = JSON.parse(inputStr);

    if (inputData.status === "FAILED" || !inputData.data || inputData.data.length === 0) {
       console.log(JSON.stringify({ status: "SKIPPED", role: "Output(Distribution)", msg: "No items to post." }, null, 2));
       return;
    }

    const results = [];

    // 2. Loop through approved items and Dispatch to Socials
    for (const item of inputData.data) {
        // Image URL from Creatomate static render
        const imageUrl = item.static_render?.url || item.render_job?.url || item.url;

        if (!imageUrl) {
            console.error(JSON.stringify({ status: "SKIPPED", msg: "Missing Image URL for Posting." }));
            continue;
        }

        const scriptJson = item.generated_script || {};
        const reel = scriptJson.reel_script || scriptJson;
        
        // Use the exact pre-formatted caption generated by Gemini if available
        let caption = scriptJson.caption;
        if (!caption) {
            caption = `${reel.hook || item.source_article?.title}\n\n${reel.body || ''}\n\n${reel.cta || '#เกมปังv2 #panggame'}`.trim();
        }

        const payload = {
            post: caption,
            platforms: ["facebook", "instagram"],
            mediaUrls: [imageUrl],
            autoHashtag: true
        };

        // 3. Fire Post to Ayrshare API
        const postRes = await fetch("https://app.ayrshare.com/api/post", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${AYRSHARE_API_KEY}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify(payload)
        });

        if (!postRes.ok) {
            const err = await postRes.text();
            throw new Error(`Ayrshare API Error: ${postRes.status} - ${err}`);
        }

        const postResponseJson = await postRes.json();

        results.push({
            ...item,
            distribution: {
                status: "PUBLISHED",
                ayrshare_id: postResponseJson.id || postResponseJson.refId,
                platforms: postResponseJson.postIds
            }
        });
    }

    // 4. Output Final System Log State (For Dashboard/Pulse Terminal)
    console.log(JSON.stringify({
      status: "SUCCESS",
      role: "Output(Distribution)",
      data: results,
      timestamp: new Date().toISOString()
    }, null, 2));

  } catch (error: any) {
    console.log(JSON.stringify({
      status: "FAILED",
      role: "Output(Distribution)",
      error: error.message,
      timestamp: new Date().toISOString()
    }, null, 2));
  }
}

run();
